// GENERATED by scripts/sync-catalog.js — do not edit. Edit src/notifications/catalog.ts,
// run `node scripts/sync-catalog.js`, and commit both files together;
// scripts/__tests__/sync-catalog.test.ts fails when they differ.

// The notification catalog (product spec §11): the single source of truth for every P0
// notification's type, category, cap class, delivery, timing and copy.
//
// It runs in three places: the app (Metro), Jest (Node) and the edge functions (Deno), where
// `scripts/sync-catalog.js` copies it to `supabase/functions/_shared/catalog.ts` under a generated
// header. So it must stay self-contained: `zod` only — no `@/` alias, no React Native, no Node
// built-ins, no `expo-router` types (urls are plain path strings; Expo Router's groups drop out of
// them, so `/trips/<id>/summary` is the D1 route `/(app)/trips/[clientTripId]/summary`).
//
// Delivery (cross-plan ruling, rev1: C1): the drive summary is LOCAL — scheduled on the phone at
// finalize by M3's `summaryNotifier`, which takes its words from `renderLocal` and nothing else.
// `push-sender` refuses every `delivery: 'local'` type. Pushed types take their words from
// `renderPush`. Non-live rows are reserved for the milestone that builds their producer and carry
// no copy until then: a notification for a feature that does not exist would promise it.
//
// Honesty: no string here may assert what the data does not support. The drive summary names no
// score (it is provisional at finalize) and no place (§11.1 rule 5, the lock screen).
import { z } from 'zod';

// ——— vocabulary ———

/** Every P0 row of §11.2. */
export type NotificationType =
  | 'trip_summary'
  | 'permission_lapsed'
  | 'missed_drive'
  | 'streak_milestone'
  | 'goal_completed'
  | 'level_up'
  | 'referral_qualified'
  | 'family_membership'
  | 'family_sharing_changed'
  | 'family_digest'
  | 'data_export_ready'
  | 'transparency_reminder';

/** H6's switches; `recording` is the §11.1 rule 3 addition (every category individually switchable). */
export type NotificationCategory =
  | 'trip_summaries'
  | 'recording'
  | 'rewards'
  | 'family'
  | 'safety'
  | 'product'
  | 'weekly_recap'
  | 'crews';

/** How §11.1 rule 2 treats a type: `family` and `critical` are exempt from the daily cap. */
export type CapClass = 'standard' | 'family' | 'promo' | 'critical';

/** `local`: scheduled by the phone itself. `push`: sent by `push-sender`. */
export type Delivery = 'local' | 'push';

export type AndroidChannel = 'trips' | 'recording_problems' | 'family' | 'rewards';

export type Producer = 'M3' | 'M4' | 'M5' | 'M6' | 'M8' | 'unassigned';

/** A local-time window, `HH:MM` 24-hour. Delivery outside it is deferred to its next start. */
export interface DeliveryWindow {
  start: string;
  end: string;
}

export interface CatalogEntry {
  type: NotificationType;
  category: NotificationCategory;
  capClass: CapClass;
  priority: 'normal' | 'low';
  androidChannel: AndroidChannel;
  delivery: Delivery;
  producer: Producer;
  /** Produced and delivered in this build. Only live types have a payload schema and copy. */
  live: boolean;
  /** After this many hours undelivered, the item is stale and is never sent. */
  ttlHours: number;
  window?: DeliveryWindow;
  /** At most this many per rolling 7 days. */
  weeklyLimit?: number;
}

// ——— the cap (§11.1 rule 2) ———

/** "≤ 2 non-family notifications per day, ≤ 1 promotional/product per week." */
export const DAILY_CAP = { nonFamilyPerDay: 2, promoPer7Days: 1 } as const;

/**
 * OPEN PRODUCT QUESTION (pending with the user): does a drive summary count toward the daily cap?
 * The M4 ledger's reading of §11.1 is yes — rule 2 caps every non-family notification and exempts
 * only family and crash alerts, and §11.2 lists "Trip summary ready" as a notification — so a
 * driver with three drives in a day gets at most two summary notifications (batching keeps it
 * lower). Flip this one constant if the user rules drive summaries transactional. Both halves of
 * the cap (the phone's `localDeliveryPlan` and `push-sender`) read it through `countsTowardDailyCap`.
 */
export const DRIVE_SUMMARY_COUNTS_TOWARD_DAILY_CAP = true;

// ——— the catalog ———

const entry = <T extends NotificationType>(e: CatalogEntry & { type: T }): CatalogEntry & { type: T } => e;

export const CATALOG = {
  // Live.
  trip_summary: entry({
    type: 'trip_summary',
    category: 'trip_summaries',
    capClass: 'standard',
    priority: 'normal',
    androidChannel: 'trips',
    delivery: 'local',
    producer: 'M3',
    live: true,
    ttlHours: 12,
  }),
  permission_lapsed: entry({
    type: 'permission_lapsed',
    category: 'recording',
    capClass: 'standard',
    priority: 'normal',
    androidChannel: 'recording_problems',
    delivery: 'push',
    producer: 'M4',
    live: true,
    ttlHours: 24,
  }),
  // Reserved: no producer, no copy yet.
  missed_drive: entry({
    type: 'missed_drive',
    category: 'recording',
    capClass: 'standard',
    priority: 'low',
    androidChannel: 'recording_problems',
    delivery: 'push',
    producer: 'unassigned',
    live: false,
    ttlHours: 24,
    window: { start: '08:00', end: '11:00' },
    weeklyLimit: 1,
  }),
  streak_milestone: entry({
    type: 'streak_milestone',
    category: 'rewards',
    capClass: 'standard',
    priority: 'low',
    androidChannel: 'rewards',
    delivery: 'push',
    producer: 'M5',
    live: false,
    ttlHours: 24,
    window: { start: '18:00', end: '20:30' },
  }),
  goal_completed: entry({
    type: 'goal_completed',
    category: 'rewards',
    capClass: 'standard',
    priority: 'low',
    androidChannel: 'rewards',
    delivery: 'push',
    producer: 'M5',
    live: false,
    ttlHours: 48,
  }),
  level_up: entry({
    type: 'level_up',
    category: 'rewards',
    capClass: 'standard',
    priority: 'low',
    androidChannel: 'rewards',
    delivery: 'push',
    producer: 'M5',
    live: false,
    ttlHours: 48,
  }),
  referral_qualified: entry({
    type: 'referral_qualified',
    category: 'rewards',
    capClass: 'standard',
    priority: 'normal',
    androidChannel: 'rewards',
    delivery: 'push',
    producer: 'M5',
    live: false,
    ttlHours: 48,
  }),
  family_membership: entry({
    type: 'family_membership',
    category: 'family',
    capClass: 'family',
    priority: 'normal',
    androidChannel: 'family',
    delivery: 'push',
    producer: 'M6',
    live: false,
    ttlHours: 72,
  }),
  family_sharing_changed: entry({
    type: 'family_sharing_changed',
    category: 'family',
    capClass: 'family',
    priority: 'normal',
    androidChannel: 'family',
    delivery: 'push',
    producer: 'M6',
    live: false,
    ttlHours: 72,
  }),
  family_digest: entry({
    type: 'family_digest',
    category: 'family',
    capClass: 'family',
    priority: 'normal',
    androidChannel: 'family',
    delivery: 'push',
    producer: 'M6',
    live: false,
    ttlHours: 72,
  }),
  data_export_ready: entry({
    type: 'data_export_ready',
    category: 'product',
    capClass: 'standard',
    priority: 'normal',
    androidChannel: 'trips',
    delivery: 'push',
    producer: 'M8',
    live: false,
    ttlHours: 72,
  }),
  transparency_reminder: entry({
    type: 'transparency_reminder',
    category: 'family',
    capClass: 'promo',
    priority: 'low',
    androidChannel: 'family',
    delivery: 'push',
    producer: 'M6',
    live: false,
    ttlHours: 168,
  }),
} as const satisfies { [K in NotificationType]: CatalogEntry & { type: K } };

/** The live types, in catalog order. Equals the `inbox.type` CHECK (Task 20 asserts it). */
export const LIVE_TYPES = ['trip_summary', 'permission_lapsed'] as const;
export type LiveType = (typeof LIVE_TYPES)[number];

/** Whether a notification of `type` uses up one of the day's `DAILY_CAP.nonFamilyPerDay`. */
export function countsTowardDailyCap(type: NotificationType): boolean {
  if (type === 'trip_summary') return DRIVE_SUMMARY_COUNTS_TOWARD_DAILY_CAP;
  const cls = CATALOG[type].capClass;
  return cls === 'standard' || cls === 'promo';
}

// ——— payloads (live types only) ———

export const PayloadSchemas = {
  trip_summary: z
    .object({
      clientTripId: z.string().regex(/^[A-Za-z0-9_-]{1,64}$/),
      startedAt: z.string(),
      endedAt: z.string(),
      distanceM: z.number().min(0),
      status: z.enum(['provisional', 'final', 'unscored']),
      roleUnknown: z.boolean(),
    })
    .strict(),
  permission_lapsed: z
    .object({
      permission: z.enum(['location_always', 'location', 'motion']),
      platform: z.enum(['ios', 'android']),
      deviceId: z.string().max(128),
    })
    .strict(),
} as const;

export type TripSummaryPayload = z.infer<typeof PayloadSchemas.trip_summary>;
export type PermissionLapsedPayload = z.infer<typeof PayloadSchemas.permission_lapsed>;

// ——— copy ———

export interface LocalCopy {
  title: string;
  body: string;
  url: string;
  /** The *I drove / Passenger* action category, only when the driver must say who drove. */
  categoryId?: 'trip_role';
  channelId: 'trips';
}

export interface PushCopy {
  title: string;
  body: string;
  url: string;
  channelId: AndroidChannel;
}

export interface InboxCopy {
  title: string;
  body: string;
  url: string;
}

export interface TripSummaryFacts {
  clientTripId: string;
  distanceM: number;
  roleUnknown: boolean;
  /** How many drives this notification announces (M3 batches drives that end close together). */
  count: number;
}

const METERS_PER_MILE = 1609.344;

/** "3.2" under ten miles, whole miles above; null when there is no distance worth naming. */
function miles(distanceM: number): string | null {
  const mi = distanceM / METERS_PER_MILE;
  if (!Number.isFinite(mi) || mi < 0.05) return null;
  return mi < 9.95 ? mi.toFixed(1) : String(Math.round(mi));
}

/**
 * The drive-summary notification, the one copy M3's notifier shows. No score (provisional at
 * finalize), no places. A batch goes to the list, where each drive — role-unknown ones included —
 * is answered on its own.
 */
export function renderLocal(type: 'trip_summary', facts: TripSummaryFacts): LocalCopy {
  void type;
  if (facts.count >= 2) {
    return {
      title: `${facts.count} drives are ready`,
      body: 'Tap to see how they went.',
      url: '/trips',
      channelId: 'trips',
    };
  }
  const mi = miles(facts.distanceM);
  const url = `/trips/${facts.clientTripId}/summary`;
  if (facts.roleUnknown) {
    return {
      title: 'Were you driving?',
      body:
        mi === null
          ? 'Tell us who drove this trip so it can be scored.'
          : `Tell us who drove your ${mi} mi trip so it can be scored.`,
      url,
      categoryId: 'trip_role',
      channelId: 'trips',
    };
  }
  return {
    title: 'Drive summary ready',
    body:
      mi === null
        ? 'Your drive is ready. Tap to see how it went.'
        : `Your ${mi} mi drive is ready. Tap to see how it went.`,
    url,
    channelId: 'trips',
  };
}

const LAPSE_COPY: Record<PermissionLapsedPayload['permission'], { title: string; body: string }> = {
  location_always: {
    title: 'Automatic recording is off',
    body: "RoadWise can't start drives on its own right now. Tap to fix it.",
  },
  location: {
    title: 'Drive recording is off',
    body: "Location access is off, so drives can't be recorded. Tap to fix it.",
  },
  motion: {
    title: 'Drive detection needs attention',
    body: 'Motion access is off, so drives are harder to detect. Tap to fix it.',
  },
};

/**
 * Push copy for a live `delivery: 'push'` type. Null for a local type (never pushed), a non-live
 * type (no copy yet) and a payload that fails its schema (nothing true to say).
 */
export function renderPush(type: NotificationType, payload: unknown): PushCopy | null {
  const e = CATALOG[type];
  if (!e.live || e.delivery !== 'push') return null;
  if (type === 'permission_lapsed') {
    const p = PayloadSchemas.permission_lapsed.safeParse(payload);
    if (!p.success) return null;
    return { ...LAPSE_COPY[p.data.permission], url: '/permissions', channelId: e.androidChannel };
  }
  return null;
}

/**
 * The inbox row's base copy. A drive summary is built from `renderLocal` with `count: 1`, so the
 * words match the notification the driver saw; the inbox (Task 6) then replaces the variant from
 * the trip's current state. Null where `renderPush` would be null for a pushed type.
 */
export function renderInboxBase(type: NotificationType, payload: unknown): InboxCopy | null {
  if (type === 'trip_summary') {
    const p = PayloadSchemas.trip_summary.safeParse(payload);
    if (!p.success) return null;
    const { title, body, url } = renderLocal('trip_summary', {
      clientTripId: p.data.clientTripId,
      distanceM: p.data.distanceM,
      roleUnknown: p.data.roleUnknown,
      count: 1,
    });
    return { title, body, url };
  }
  const pushed = renderPush(type, payload);
  return pushed === null ? null : { title: pushed.title, body: pushed.body, url: pushed.url };
}

/**
 * Promises and claims no notification may make (rev1: m, narrowed to promises): score guarantees,
 * deletion and export (M8 is not built), streak pressure (§11.1 rule 6), rewards (M5 is not
 * built), and exclamation marks (factual and warm, not loud).
 */
export const BANNED_COPY: readonly RegExp[] = [
  /never lowers|driving less|nothing is lost|can(no|')t go down|never decays/i,
  /(can|will) delete|delete (everything|your)|export your|download your data/i,
  /lose your streak|about to lose|hurry|last chance/i,
  /reward|points/i,
  /!/,
];
