import { readFileSync } from 'node:fs';

// eslint-disable-next-line @typescript-eslint/no-require-imports -- a CommonJS Node script
const { SOURCE, TARGET, HEADER, render, inSync } = require('../sync-catalog.js') as {
  SOURCE: string;
  TARGET: string;
  HEADER: string;
  render: (source: string) => string;
  inSync: (source: string, target: string) => boolean;
};

const source = () => readFileSync(SOURCE, 'utf8');
const target = () => readFileSync(TARGET, 'utf8');

test('the edge-function copy of the catalog is the source under a generated header', () => {
  expect(target()).toBe(HEADER + source());
  expect(inSync(source(), target())).toBe(true);
});

test('the header says it is generated and where to edit', () => {
  expect(HEADER).toMatch(/GENERATED by scripts\/sync-catalog\.js/);
  expect(HEADER).toMatch(/src\/notifications\/catalog\.ts/);
});

test('a copy that differs from the source by one character is out of sync', () => {
  const src = source();
  const drifted = render(src).replace('Drive summary ready', 'Drive summary Ready');
  expect(inSync(src, drifted)).toBe(false);
  expect(inSync(src + '\n', render(src))).toBe(false);
});

/** Every module specifier in `src`: import/export … from, bare import, dynamic import, require. */
const specifiers = (src: string) => [
  ...[...src.matchAll(/^\s*(?:import|export)\b[^;]*?\bfrom\s*["']([^"']+)["']/gm)].map((m) => m[1]),
  ...[...src.matchAll(/^\s*import\s*["']([^"']+)["']/gm)].map((m) => m[1]),
  ...[...src.matchAll(/\b(?:import|require)\s*\(\s*["']([^"']+)["']/g)].map((m) => m[1]),
];

test('the catalog stays portable: it imports zod and nothing else', () => {
  expect(specifiers(source())).toEqual(['zod']);
});

test('the portability scan sees every import form', () => {
  const src = [
    'import { a } from "x1";',
    "export { b } from 'x2';",
    "export * from 'x3';",
    "import 'x4';",
    "const c = await import('x5');",
    'const d = require("x6");',
  ].join('\n');
  expect(specifiers(src).sort()).toEqual(['x1', 'x2', 'x3', 'x4', 'x5', 'x6']);
});
