#!/usr/bin/env node
'use strict';
/**
 * Copies the notification catalog (src/notifications/catalog.ts) to
 * supabase/functions/_shared/catalog.ts under a generated header, so `push-sender` decides and
 * words every notification with exactly the code the app ships.
 *
 *   node scripts/sync-catalog.js
 *
 * A plain copy works because the catalog imports only `zod`, which the edge functions' import map
 * already pins to the app's installed version (scripts/sync-scoring.js writes that entry). This
 * script touches nothing else: not deno.json, not sync-scoring.js's trees.
 *
 * scripts/__tests__/sync-catalog.test.ts fails the moment the two differ, so run this after every
 * change to the catalog and commit both files together.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SOURCE = path.join(ROOT, 'src', 'notifications', 'catalog.ts');
const TARGET = path.join(ROOT, 'supabase', 'functions', '_shared', 'catalog.ts');

const HEADER =
  '// GENERATED by scripts/sync-catalog.js — do not edit. Edit src/notifications/catalog.ts,\n' +
  '// run `node scripts/sync-catalog.js`, and commit both files together;\n' +
  '// scripts/__tests__/sync-catalog.test.ts fails when they differ.\n\n';

/** The generated copy of `source`. */
const render = (source) => HEADER + source;

/** Whether `target` is exactly the generated copy of `source`. */
const inSync = (source, target) => target === render(source);

function sync() {
  const source = fs.readFileSync(SOURCE, 'utf8');
  fs.writeFileSync(TARGET, render(source));
  console.log('catalog: synced src/notifications/catalog.ts to supabase/functions/_shared/catalog.ts');
}

module.exports = { SOURCE, TARGET, HEADER, render, inSync, sync };

if (require.main === module) sync();
