#!/usr/bin/env node
'use strict';
/**
 * Copies packages/scoring/src into supabase/functions/_shared/scoring, so the edge function that
 * re-scores a trip server-side runs exactly the code the app ran on the device, and copies the
 * upload contract (src/data/sync/payload.ts) to supabase/functions/_shared/payload.ts, so the
 * server validates exactly what the device validated before queueing.
 *
 *   npm run scoring:sync
 *
 * A plain file copy works because both sources are deliberately dependency-free: the scoring
 * package imports nothing outside its own directory, and the payload contract imports only `zod`.
 * That makes the copied tree a valid Deno module graph once `deno.json` maps `zod` to the npm
 * package at the version the app has installed (node_modules/zod/package.json), which this sync
 * also writes — the two ends then agree on the schema *and* on the validator.
 *
 * It also mirrors the speed-limit contract, tile math and matcher (src/core/speedLimits/{wire,tiles,
 * match,geometry}.ts) into supabase/functions/_shared/speedLimits, so the `speed-limits` function
 * validates, cuts tiles and matches roads with exactly the code the device runs. That list is
 * explicit: the device-only client, api and store live in the same folder and must never be copied.
 * The same import map pins `aws4fetch`, the SigV4 signer the function's AWS fallback uses.
 *
 * scripts/__tests__/sync-scoring.test.ts fails the moment any of them drift, so run this after
 * every change under packages/scoring/src, src/data/sync/payload.ts or the four speed-limit files,
 * and commit the result.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'packages', 'scoring', 'src');
const PAYLOAD_SRC = path.join(ROOT, 'src', 'data', 'sync', 'payload.ts');
const FUNCTIONS = path.join(ROOT, 'supabase', 'functions');
const SHARED = path.join(FUNCTIONS, '_shared');
const DST = path.join(SHARED, 'scoring');
const PAYLOAD_DST = path.join(SHARED, 'payload.ts');
const DENO_JSON = path.join(FUNCTIONS, 'deno.json');
const ZOD_PKG = path.join(ROOT, 'node_modules', 'zod', 'package.json');
const README = 'README.md';
/** Every generated import-map key starts with this, so a re-sync can replace exactly its own keys. */
const MAP_PREFIX = './_shared/scoring/';

const SPEED_SRC = path.join(ROOT, 'src', 'core', 'speedLimits');
const SPEED_DST = path.join(SHARED, 'speedLimits');
/**
 * The speed-limit modules the function shares with the device, by explicit list. Each imports only
 * its siblings and `zod`. `client.ts`, `api.ts` and `store.ts` are device-only and stay out.
 */
const SPEED_FILES = ['geometry.ts', 'match.ts', 'tiles.ts', 'wire.ts'];
/** The second generated key family; like MAP_PREFIX, a re-sync replaces exactly these keys. */
const SPEED_MAP_PREFIX = './_shared/speedLimits/';
/** SigV4 for the speed-limits AWS fallback. Not an app dependency, so pinned here. */
const AWS4FETCH = 'npm:aws4fetch@1.0.20';

const README_TEXT = `# scoring (generated)

GENERATED by scripts/sync-scoring.js — edit packages/scoring instead.

Every file beside this one is a byte-for-byte copy of \`packages/scoring/src\`. Edit the package,
run \`npm run scoring:sync\`, and commit both trees together; \`scripts/__tests__/sync-scoring.test.ts\`
fails when they differ.

The modules only ever import each other by relative path, which is what makes a plain copy work.
Those specifiers are extensionless (\`./constants\`) and Deno will not resolve them on its own, so the
same sync also generates the \`imports\` map in \`supabase/functions/deno.json\` — one entry per module.
That map is generated too: add or remove a module in the package and re-run the sync, never hand-edit
it. Rewriting the specifiers in this copy is not an option; it has to stay byte-identical.

The same sync copies the upload contract to \`../payload.ts\` (from \`src/data/sync/payload.ts\`) and
pins \`zod\` in the import map to the version the app has installed; both are generated the same way.

Deno finds that config by walking up from the working directory, which is what \`supabase functions\`
does. Checking the copy by hand from the repo root needs it spelled out:

    deno check --config supabase/functions/deno.json supabase/functions/_shared/scoring/index.ts
`;

fs.mkdirSync(DST, { recursive: true });

const sources = fs.readdirSync(SRC).filter((f) => fs.statSync(path.join(SRC, f)).isFile());
for (const name of sources) {
  fs.copyFileSync(path.join(SRC, name), path.join(DST, name));
}

// Drop whatever an earlier sync left behind, so the copy is the package and nothing else.
const keep = new Set(sources);
keep.add(README);
for (const name of fs.readdirSync(DST)) {
  if (!keep.has(name)) fs.rmSync(path.join(DST, name), { recursive: true, force: true });
}

fs.writeFileSync(path.join(DST, README), README_TEXT);

// The upload contract, verbatim: the server must refuse exactly what the device refuses.
fs.copyFileSync(PAYLOAD_SRC, PAYLOAD_DST);

// The speed-limit modules, verbatim, and nothing else in their folder.
const SPEED_README_TEXT = `# speedLimits (generated)

GENERATED by scripts/sync-scoring.js — edit src/core/speedLimits instead.

Every file beside this one is a byte-for-byte copy of one of \`src/core/speedLimits/{${SPEED_FILES.map((f) =>
  f.replace(/\.ts$/, '')
).join(',')}}.ts\`, so the \`speed-limits\` function validates its answers, reads tile keys and matches
roads with exactly the code the device runs. Edit the source, run \`npm run scoring:sync\`, and commit
both together; \`scripts/__tests__/sync-scoring.test.ts\` fails when they differ. The extensionless
sibling imports resolve through the generated \`imports\` map in \`supabase/functions/deno.json\`.
`;
fs.mkdirSync(SPEED_DST, { recursive: true });
for (const name of SPEED_FILES) {
  fs.copyFileSync(path.join(SPEED_SRC, name), path.join(SPEED_DST, name));
}
const speedKeep = new Set([...SPEED_FILES, README]);
for (const name of fs.readdirSync(SPEED_DST)) {
  if (!speedKeep.has(name)) fs.rmSync(path.join(SPEED_DST, name), { recursive: true, force: true });
}
fs.writeFileSync(path.join(SPEED_DST, README), SPEED_README_TEXT);

// Deno resolves relative specifiers literally, so `./constants` inside the copy is a 404 to it and
// `deno check` fails on every module. The package cannot carry `.ts` specifiers (Metro and tsc would
// both object) and the copy has to stay byte-identical, so the extension is supplied out of band, by
// an import map. Other keys in an existing deno.json are left alone; ours are rewritten wholesale so
// a module deleted from the package also disappears from the map.
const config = fs.existsSync(DENO_JSON) ? JSON.parse(fs.readFileSync(DENO_JSON, 'utf8')) : {};
const imports = config.imports || {};
for (const key of Object.keys(imports)) {
  if (key.startsWith(MAP_PREFIX) || key.startsWith(SPEED_MAP_PREFIX)) delete imports[key];
}
for (const name of sources) {
  imports[MAP_PREFIX + name.replace(/\.ts$/, '')] = MAP_PREFIX + name;
}
for (const name of SPEED_FILES) {
  imports[SPEED_MAP_PREFIX + name.replace(/\.ts$/, '')] = SPEED_MAP_PREFIX + name;
}
imports.aws4fetch = AWS4FETCH;
// The contract's one dependency, at the app's installed version: `import { z } from 'zod'` in the
// copy resolves to the same validator the device ran.
const zodVersion = JSON.parse(fs.readFileSync(ZOD_PKG, 'utf8')).version;
imports.zod = `npm:zod@${zodVersion}`;
config.imports = Object.fromEntries(
  Object.entries(imports).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
);
fs.writeFileSync(DENO_JSON, JSON.stringify(config, null, 2) + '\n');

console.log(
  `scoring: synced ${sources.length} file(s) to supabase/functions/_shared/scoring, ` +
    `the upload contract to supabase/functions/_shared/payload.ts, ${SPEED_FILES.length} speed-limit ` +
    `file(s) to supabase/functions/_shared/speedLimits, and mapped them ` +
    `(zod@${zodVersion}) in supabase/functions/deno.json`
);
