#!/usr/bin/env node
'use strict';
/**
 * Copies packages/scoring/src into supabase/functions/_shared/scoring, so the edge function that
 * re-scores a trip server-side runs exactly the code the app ran on the device.
 *
 *   npm run scoring:sync
 *
 * A plain file copy works because the scoring package is deliberately dependency-free: no imports
 * outside its own directory, no Node built-ins, no React Native. That makes the copied tree a valid
 * Deno module graph as-is.
 *
 * scripts/__tests__/sync-scoring.test.ts fails the moment the two trees drift, so run this after
 * every change under packages/scoring/src and commit the result.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'packages', 'scoring', 'src');
const DST = path.join(ROOT, 'supabase', 'functions', '_shared', 'scoring');
const README = 'README.md';

const README_TEXT = `# scoring (generated)

GENERATED by scripts/sync-scoring.js — edit packages/scoring instead.

Every file beside this one is a byte-for-byte copy of \`packages/scoring/src\`. Edit the package,
run \`npm run scoring:sync\`, and commit both trees together; \`scripts/__tests__/sync-scoring.test.ts\`
fails when they differ.

The modules only ever import each other by relative path, which is what makes a plain copy work. The
specifiers are extensionless (\`./constants\`), so the function importing this tree has to tell Deno
how to resolve them — a \`deno.json\` with sloppy-imports, or an import map. Rewriting them here is not
an option: the copy has to stay byte-identical to the package.
`;

fs.mkdirSync(DST, { recursive: true });

const sources = fs.readdirSync(SRC).filter((f) => fs.statSync(path.join(SRC, f)).isFile());
for (const name of sources) {
  fs.copyFileSync(path.join(SRC, name), path.join(DST, name));
}

// Drop whatever an earlier sync left behind, so the copy is the package and nothing else.
const keep = new Set(sources);
keep.add(README);
for (const name of fs.readdirSync(DST)) {
  if (!keep.has(name)) fs.rmSync(path.join(DST, name), { recursive: true, force: true });
}

fs.writeFileSync(path.join(DST, README), README_TEXT);

console.log(`scoring: synced ${sources.length} file(s) to supabase/functions/_shared/scoring`);
