import type { Href } from 'expo-router';

/**
 * The words on the drive screens (C3, C4c, C6, the lockout card and the in-progress banner).
 *
 * Anything a driver may see while moving holds to SR3: three words at most, no sentence to read.
 * The stopped panel and the banner appear only while stopped or on a parked phone, so they may say
 * a little more, but each control still names its action. Spoken-only strings (screen-reader
 * labels, the stopped announcement) may be full sentences: they are heard, not read.
 *
 * English only for M3 (ruling U1 concern 3); the M8 i18n pass moves these into `en.ts`.
 */
export const hudCopy = {
  hud: {
    /** The full-screen shield while locked: a screen reader's name for it. */
    shieldLabel: 'Drive screen. Touch and hold to mute the alert.',
  },
  stopped: {
    endDrive: 'End drive',
    muteDrive: 'Mute alerts for this drive',
    mutedDrive: 'Alerts muted for this drive',
    passengerNow: "I'm a passenger now",
    drivingNow: "I'm driving now",
    /** C6 A11y: announced as the panel appears. */
    announcement: 'Vehicle stopped. End drive button.',
    panelLabel: 'Stopped panel',
  },
  pocket: {
    recording: 'Recording',
    /** `ending`: the car has been still for minutes and the drive may end on its own. */
    stopped: 'Stopped',
    passenger: 'Passenger',
    /** Screen-reader hint for the whole pocket screen. */
    hintStopped: 'Tap to show the drive controls.',
  },
  parked: {
    /** SR3: three words, shown while moving (SR8). */
    title: 'Available when parked',
    recording: 'Recording',
    label: "RoadWise is available when you're parked.",
    labelRecording: "RoadWise is available when you're parked. Your drive is recording.",
  },
  banner: {
    title: 'Drive in progress',
    passenger: "I'm a passenger",
    driving: "I'm driving",
    endDrive: 'End drive',
    openHud: 'Open HUD',
    useMounted: 'Use as mounted HUD',
    passengerStamp: 'PASSENGER',
  },
} as const;

/**
 * The drive routes as `usePathname()` reports them — the names U3's sheet and end screen, U4's
 * banner host and H2's root layout coordinate on. `driveHref` casts one for `router`: the
 * typed-routes union is generated by the dev server and lags new files (U3 and U4 cast likewise).
 */
export const DRIVE_ROUTES = {
  start: '/drive/start',
  hud: '/drive/hud',
  pocket: '/drive/pocket',
  end: '/drive/end',
} as const;
export const DRIVE_GROUP_PREFIX = '/drive/';
export const driveHref = (route: string): Href => route as Href;
