import type { Href } from 'expo-router';

/**
 * The words on the drive screens (C3, C4c, C6, the lockout card and the in-progress banner).
 *
 * Anything a driver may see while moving holds to SR3: three words at most, no sentence to read.
 * The stopped panel and the in-progress banner appear only while stopped or on a parked phone, so
 * they may say a little more, but each control still names its action. Spoken-only strings
 * (screen-reader labels and hints, the stopped announcement) may be full sentences: they are
 * heard, not read.
 *
 * English only for M3 (ruling U1 concern 3); the M8 i18n pass moves these into `en.ts`.
 */
export const hudCopy = {
  /** The mounted HUD (C3): its two hold-to-act controls and the trip timer. */
  hud: {
    sos: 'SOS',
    sosLabel: 'Emergency call',
    sosHint: 'Hold for two seconds to open the phone dialer with the emergency number.',
    end: 'End drive',
    endLabel: 'End drive',
    endHint: 'Hold for two seconds to end the drive.',
    timerLabel: (hours: number, minutes: number) =>
      `Driving for ${hours} ${hours === 1 ? 'hour' : 'hours'} and ${minutes} ${minutes === 1 ? 'minute' : 'minutes'}`,
  },
  /** The top bar's one weather hazard (Open-Meteo), two words at most. */
  hazard: {
    thunderstorm: 'Thunderstorm',
    icy_rain: 'Icy rain',
    heavy_snow: 'Heavy snow',
    dense_fog: 'Dense fog',
    heavy_rain: 'Heavy rain',
    strong_wind: 'Strong wind',
    label: (words: string) => `Weather hazard: ${words}`,
  },
  /** The event banner: a few seconds of words during or just after a high-risk event. */
  event: {
    braking: 'Hard braking',
    accel: 'Rapid acceleration',
    cornering: 'Sharp turn',
    speeding: 'Slow down',
    phone: 'Phone down',
    eyes_off: 'Eyes on road',
    drowsy: 'Take a break',
    break: 'Take a break',
    /** Under "Take a break" on the two-hour suggestion: how long the drive has run. */
    breakDetail: (hours: number) => `${hours} h driving`,
  },
  alerts: {
    /** SR3: three words; shown when the alert sounds failed to load (ruling H2 item 6). */
    unavailable: 'Sound alerts unavailable',
    label: 'Sound alerts unavailable. This drive is still recording.',
  },
  stopped: {
    endDrive: 'End drive',
    muteDrive: 'Mute alerts for this drive',
    mutedDrive: 'Alerts muted for this drive',
    passengerNow: "I'm a passenger now",
    drivingNow: "I'm driving now",
    /** C6 A11y: announced as the panel appears. */
    announcement: 'Vehicle stopped. End drive button.',
    panelLabel: 'Stopped panel',
  },
  pocket: {
    recording: 'Recording',
    /** `ending`: the car has been still for minutes and the drive may end on its own. */
    stopped: 'Stopped',
    passenger: 'Passenger',
    /** Screen-reader hint for the whole pocket screen. */
    hintStopped: 'Tap to show the drive controls.',
  },
  parked: {
    /** SR3: three words, shown while moving (SR8). */
    title: 'Available when parked',
    recording: 'Recording',
    label: "RoadWise is available when you're parked.",
    labelRecording: "RoadWise is available when you're parked. Your drive is recording.",
  },
  banner: {
    title: 'Drive in progress',
    passenger: "I'm a passenger",
    driving: "I'm driving",
    endDrive: 'End drive',
    openHud: 'Open HUD',
    useMounted: 'Use as mounted HUD',
    passengerStamp: 'PASSENGER',
  },
} as const;

/**
 * The drive routes as `usePathname()` reports them — the names U3's sheet and end screen, U4's
 * banner host and H2's root layout coordinate on. `driveHref` casts one for `router`: the
 * typed-routes union is generated by the dev server and lags new files (U3 and U4 cast likewise).
 */
export const DRIVE_ROUTES = {
  start: '/drive/start',
  hud: '/drive/hud',
  pocket: '/drive/pocket',
  end: '/drive/end',
} as const;
export const DRIVE_GROUP_PREFIX = '/drive/';
export const driveHref = (route: string): Href => route as Href;
